### PR TITLE
Smoother scrolling and simpler speed settings.

### PR DESCRIPTION
**Pull request by piitr75**

### CODE REVIEW

**Comment by sammertens** [comment]
Eyeballing the code, I like it.  Give me a chance to try it out on my own machine over the next few days, but barring any issues I'll go ahead and merge it.  Thanks.

**Comment by piitr75** [comment]
Thanks.

**Comment by sammertens** [comment]
Merged.  I reserve the right to mess with the default setting (because, hey, my repository), but yes, it's cleaner than what I had before.

**Comment by piitr75** [comment]
OK, thank you.

**Pull request merged**
